### ISSUE TITLE
Agregar botones funcionales de eliminar y editar

### ISSUE THREAD

**Issue by sneydermc3007** [Code-Jathon/Bessie#12]

**Comment by sneydermc3007** [comment]
@JuanJoseMA2020 usted va recibir apoyo de @bryanariasq02  ya que el finalizo sus actividades

**Comment by JuanJoseMA2020** [comment]
Buenas tardes, @sneydermc3007 @bryanariasq02 @Daniel7R ya quedó unido el codigo funcional con los cambios en las vistas y con el error de parámetro desconocido a la hora de agregar. Sugiero que para seguir trabajando en el boton de editar se haga desde esta rama para evitar conflictos con el Merge. Ya agrega articulo y ya elimina, @Daniel7R puede continuar con editar pero le recomiento que sea desde esta rama.
