### ISSUE TITLE
Inicio Sesion --> Backend & Google Sheets

### ISSUE THREAD

**Issue by sneydermc3007** [Code-Jathon/Bessie#2]

**Comment by sneydermc3007** [comment]
Estructura base de la validación de usuario y contraseña mediante Google Sheet, además del recibimiento de los datos del **Frontend**

**Comment by sneydermc3007** [comment]
@BerrioGB se cambiara la base de datos por los _titulos_ en vez de usar **Google Sheets** usaremos **Firebase**, habla con @bryanariasq02 para que te diga como es la estructura de los datos(como debes de enviárselos) del _Log-In_ en **Firebase**.

**Comment by BerrioGB** [comment]
@sneydermc3007 @Daniel7R El backend del login esta terminado con un prototipo en HTML. A la hora de realizar el merge se conectara al front final
