### ISSUE TITLE
Menú principal --> Frontend

### ISSUE THREAD

**Issue by sneydermc3007** [Code-Jathon/Bessie#4]

**Comment by sneydermc3007** [comment]
Creación del dashboard con un sidebar para la navegación, se debe trabajar con datos quemados siempre y cuando no se hayan proporcionado datos en caso contrario utilizar los articulos correspondientes.

**Comment by camilogs1** [comment]
Done

**Comment by sneydermc3007** [comment]
@camilogs1 La rama `Main-menu` se dejara de usar y ahora los cambios referentes al menú principal se harán en la rama `main_menu-frontend`
